# Generated by Django 5.1.4 on 2024-12-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=17, null=True)),
                ('vehicle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_brand', models.CharField(blank=True, max_length=15, null=True)),
                ('vehicle_cliente', models.CharField(blank=True, max_length=80, null=True)),
                ('vehicle_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('distribuidorax', models.CharField(blank=True, max_length=400, null=True)),
                ('costAbonado', models.CharField(blank=True, max_length=12, null=True)),
                ('costTotal', models.CharField(blank=True, max_length=12, null=True)),
                ('problem_description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Consulta', 'Consulta'), ('Pendiente de investigar', 'Pendiente de investigar'), ('Pendiente de enviar', 'Pendiente de enviar'), ('Enviado', 'Enviado')], default='Pendiente de enviar', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('Consulta', 'Consulta'), ('Abonado', 'Abonado'), ('Cotizado', 'Cotizado'), ('Pagado', 'Pagado')], default='Consultado', max_length=50, null=True)),
                ('dinomoDis', models.CharField(choices=[('Vacio', 'Vacio'), ('Solicitado pero pendiente de enviarmelo', 'Solicitado pero pendiente de enviarmelo'), ('Completado', 'Completado'), ('Investigar', 'Investigar')], default='Vacio', max_length=50, null=True)),
            ],
        ),
    ]
