# Generated by Django 5.1.4 on 2024-12-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_blog', models.CharField(max_length=255)),
                ('resumen_blog', models.TextField()),
                ('caracteristica_blog', models.CharField(max_length=255)),
                ('explicacion_blog', models.TextField()),
                ('youtube_blog', models.CharField(max_length=100)),
                ('codigo_blog', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('imagen_blog', models.ImageField(blank=True, null=True, upload_to='blogs/')),
            ],
        ),
    ]
