# Generated by Django 5.1.4 on 2024-12-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='codigo_blog',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo_blog',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='youtube_blog',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
