# Generated by Django 3.0.14 on 2024-06-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='category',
        ),
    ]
