# Generated by Django 3.0.5 on 2024-06-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_auto_20240601_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='vehicle_brand',
            field=models.PositiveIntegerField(),
        ),
    ]
