# Generated by Django 3.0.5 on 2024-06-04 01:45

from django.db import migrations, models
import vehicle.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_auto_20240603_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='vehicle_brand',
            field=models.PositiveIntegerField(validators=[vehicle.models.validate_positive_integer]),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_no',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
