# Generated by Django 5.0.7 on 2024-07-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_auto_20240610_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='request',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='request',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='request',
            name='cost',
        ),
        migrations.AddField(
            model_name='request',
            name='costAbonado',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='costTotal',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='dinomoDis',
            field=models.CharField(choices=[('Vacio', 'Vacio'), ('Solicitado pero pendiente de enviarmelo', 'Solicitado pero pendiente de enviarmelo'), ('Completado', 'Completado'), ('Investigar', 'Investigar')], default='Vacio', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='distribuidorax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='estado',
            field=models.CharField(choices=[('Abonado', 'Abonado'), ('Cotizado', 'Cotizado'), ('Pagado', 'Pagado')], default='Consultado', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='vehicle_cliente',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='vehicle_mobile',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='problem_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pendiente de investigar', 'Pendiente de investigar'), ('Pendiente de enviar', 'Pendiente de enviar'), ('Enviado', 'Enviado'), ('Consulta', 'Consulta')], default='Pendiente de enviar', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_brand',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Mechanic',
        ),
    ]
