# Generated by Django 5.0.7 on 2024-08-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0016_request_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='distribuidorax',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='estado',
            field=models.CharField(choices=[('Abonado', 'Abonado'), ('Cotizado', 'Cotizado'), ('Pagado', 'Pagado'), ('Consulta', 'Consulta')], default='Consultado', max_length=50, null=True),
        ),
    ]
