# Generated by Django 5.0.7 on 2024-08-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_alter_request_distribuidorax_alter_request_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='vehicle_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
