# Generated by Django 5.0.7 on 2024-08-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_alter_request_vehicle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='estado',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Abonado', 'Abonado'), ('Cotizado', 'Cotizado'), ('Pagado', 'Pagado')], default='Consultado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Pendiente de investigar', 'Pendiente de investigar'), ('Pendiente de enviar', 'Pendiente de enviar'), ('Enviado', 'Enviado')], default='Pendiente de enviar', max_length=50, null=True),
        ),
    ]
