# Generated by Django 5.1.4 on 2024-12-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canton',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Cantones'},
        ),
        migrations.AlterModelOptions(
            name='carrito',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='distrito',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'ordering': ['producto'], 'verbose_name_plural': 'Items de Carrito'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='tienda',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Tiendas'},
        ),
    ]
