# Generated by Django 5.1.4 on 2024-12-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0004_carrito_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
    ]
